In [7]:
import numpy as np
import pandas as pd
a=pd.read_csv("/content/train.csv")
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [8]:
x=a.drop(columns=["price_range"],axis=1)
y=a["price_range"]
print(x)


      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [9]:
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64


In [10]:
minimum=np.min(y)
maximum=np.max(y)
print(minimum)
print(maximum)

0
3


In [13]:
list_y=[]
for i in y:
  y_value=((i-minimum)/maximum-minimum)
  y_value=y_value*(1-0)
  list_y.append(y_value)
print(list_y)


[0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 0.6666666666666666, 0.3333333333333333, 0.3333333333333333, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.3333333333333333, 0.6666666666666666, 0.0, 0.0, 1.0, 1.0, 0.3333333333333333, 0.3333333333333333, 1.0, 1.0, 0.3333333333333333, 0.0, 0.3333333333333333, 0.6666666666666666, 1.0, 1.0, 0.6666666666666666, 0.0, 1.0, 0.0, 0.3333333333333333, 1.0, 0.0, 0.3333333333333333, 0.3333333333333333, 1.0, 0.6666666666666666, 0.6666666666666666, 0.6666666666666666, 1.0, 0.3333333333333333, 0.3333333333333333, 0.0, 0.3333333333333333, 1.0, 0.3333333333333333, 0.0, 1.0, 0.6666666666666666, 0.6666666666666666, 1.0, 0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 0.0, 1.0, 0.3333333333333333, 0.6666666666666666, 0.3333333333333333, 0.0, 0.0, 0.6666666666666666, 0.6666666666666666, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.6666666666666666, 0.0, 1.0, 0.0, 0.3333333333333333, 0.0, 0.0, 1.0, 0.3333333333333333, 1.0, 0.6666666666666666, 1.0, 0.333333333333

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x=scaler.fit_transform(x)

In [17]:
print(x)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [23]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.38476954 1.         0.8        ... 1.         0.         1.        ]
 [0.08149633 0.         0.6        ... 1.         1.         0.        ]
 [0.82832331 1.         0.         ... 1.         1.         1.        ]
 ...
 [0.22311289 0.         0.12       ... 1.         1.         1.        ]
 [0.28991316 1.         0.         ... 1.         0.         1.        ]
 [0.09151637 0.         0.48       ... 1.         1.         0.        ]]
[[0.12959252 0.         0.28       ... 1.         1.         0.        ]
 [0.23179693 1.         0.4        ... 1.         1.         1.        ]
 [0.74148297 0.         0.         ... 1.         0.         1.        ]
 ...
 [0.23380094 0.         0.         ... 1.         0.         1.        ]
 [0.6259185  1.         0.52       ... 0.         0.         0.        ]
 [0.65731463 0.         0.92       ... 1.         1.         0.        ]]
1851    3
859     2
1085    2
39      2
832     0
       ..
1032    1
1627    3
1343    2
1819    2
670     2
Na

In [25]:
data_set_2=pd.read_csv("/content/heart (1).csv")
print(data_set_2)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [33]:
x=data_set_2.drop(columns=["target"],axis=1)
y=data_set_2["target"]
print(x)


     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [34]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [35]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x=scaler.fit_transform(x)

In [36]:
print(x)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [39]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.47916667 1.         0.66666667 ... 1.         0.         1.        ]
 [0.45833333 0.         0.66666667 ... 1.         0.         0.66666667]
 [0.52083333 0.         0.66666667 ... 1.         0.25       0.66666667]
 ...
 [0.20833333 1.         0.         ... 0.5        0.         1.        ]
 [0.85416667 1.         0.66666667 ... 0.5        0.25       1.        ]
 [0.64583333 1.         0.66666667 ... 0.5        0.         0.66666667]]
[[0.75       0.         0.66666667 ... 1.         0.25       0.66666667]
 [0.33333333 1.         0.         ... 1.         0.         0.66666667]
 [0.375      1.         0.         ... 1.         0.         0.66666667]
 ...
 [0.41666667 0.         0.         ... 1.         0.         0.66666667]
 [0.72916667 0.         0.66666667 ... 1.         0.         1.        ]
 [0.125      1.         0.         ... 0.5        0.         1.        ]]
8      1
140    1
130    1
102    1
10     1
      ..
82     1
25     1
212    0
240    0
194    0
Name: target,

In [52]:
x1=x_train[0]
x2=x_train[1]
x3=x_train[2]
x4=x_train[3]
x5=x_train[4]
x6=x_train[5]
x7=x_train[6]
x8=x_train[7]
x9=x_train[8]
x10=x_train[9]
x11=x_train[10]
x12=x_train[11]
x13=x_train[12]
y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if (s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)
  return y_p

print(perceptron(1,2,3,1,2,3,1,2,3,1,2,3,1,10))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
